import { existsSync, promises as fs, readFileSync } from 'node:fs';
import path from 'node:path';
import { baseBranchFor, type AppConfig } from '../apps/apps.js';
import { commitPaths, currentBranch, withRepoLock } from '../repo/git.js';
import { findThemePreset, presetDefinition, THEME_PRESETS, type ThemeDefinition } from './presets.js';
import { renderComponentsCss, renderRepoTokensCss } from './theme-css.js';
import { THEME_DEFINITION_PATH, THEME_DIR, THEME_DOC_PATH, renderThemeDoc } from './theme-docs.js';
import { InvalidThemeError, parseThemeDefinition, sameTheme } from './theme-schema.js';

// theme/theme.json is the app's theme: the one file a human (or Riff's
// Theme page) edits. Everything else under theme/, and docs/theme.md, is
// generated from it by renderThemeFiles(). `generatedBy` marks theme/ as
// ours, so saving never overwrites a hand-written theme/ folder an
// existing repo already had.
const GENERATED_BY = 'riff-dev-sessions';

interface DefinitionFile {
  about: string;
  generatedBy: string;
  // The preset this theme started from, if any.
  basedOn: string | null;
  theme: ThemeDefinition;
}

export interface AppTheme {
  theme: ThemeDefinition;
  basedOn: string | null;
  // False when theme.json was edited by hand and the CSS hasn't been
  // regenerated from it yet.
  inSync: boolean;
}

// What the Apps list shows; read from the repo each time (same reasoning
// as readRepoUrl), since the file on disk is what the agents see.
export interface AppThemeSummary {
  name: string;
  basedOn: string | null;
  customized: boolean;
  inSync: boolean;
}

export interface ThemeApplyResult {
  theme: AppThemeSummary;
  actions: string[];
  warnings: string[];
}

export class ThemeApplyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ThemeApplyError';
  }
}

function renderThemeFiles(theme: ThemeDefinition, basedOn: string | null): Record<string, string> {
  const definition: DefinitionFile = {
    about:
      "This app's UI theme: the one place its colors, fonts, radius, spacing and shadows are defined. Edit it here or " +
      `from the app's Theme page in Riff, then regenerate. ${THEME_DIR}/*.css and ${THEME_DOC_PATH} are generated from this file.`,
    generatedBy: GENERATED_BY,
    basedOn,
    theme,
  };
  return {
    [THEME_DEFINITION_PATH]: `${JSON.stringify(definition, null, 2)}\n`,
    [`${THEME_DIR}/tokens.css`]: renderRepoTokensCss(theme, THEME_DEFINITION_PATH),
    [`${THEME_DIR}/components.css`]:
      `/* Shared ui-* components, generated by Riff Dev Sessions. They use only the tokens in tokens.css. Don't edit. */\n\n` +
      renderComponentsCss({ layer: 'ui' }),
    [`${THEME_DIR}/index.css`]: `/* Import once, at the app's root entry. See ${THEME_DOC_PATH}. */\n@import './tokens.css';\n@import './components.css';\n`,
    [THEME_DOC_PATH]: renderThemeDoc(theme),
  };
}

function readDefinitionFile(repoRoot: string): Partial<DefinitionFile> | null {
  try {
    return JSON.parse(readFileSync(path.join(repoRoot, THEME_DEFINITION_PATH), 'utf8'));
  } catch {
    return null;
  }
}

function isOurs(repoRoot: string): boolean {
  return readDefinitionFile(repoRoot)?.generatedBy === GENERATED_BY;
}

/**
 * True for the files a Riff theme generates (theme/** and docs/theme.md)
 * when the repo's theme/ is Riff's. The agents' write tools refuse these:
 * theme changes go through the theme picker, which regenerates them.
 */
export function isGeneratedThemePath(repoRoot: string, relativePath: string): boolean {
  const normalized = path.normalize(relativePath).split(path.sep).join('/');
  const generated = normalized === THEME_DOC_PATH || normalized === THEME_DIR || normalized.startsWith(`${THEME_DIR}/`);
  return generated && isOurs(repoRoot);
}

/**
 * The app's theme as its repo defines it. Throws InvalidThemeError when
 * theme.json exists but doesn't hold a valid theme (a bad hand edit); null
 * when the app has no Dev Sessions theme.
 */
export function readAppTheme(repoRoot: string): AppTheme | null {
  const exists = existsSync(path.join(repoRoot, THEME_DEFINITION_PATH));
  const file = readDefinitionFile(repoRoot);
  if (!exists || (file && file.generatedBy !== GENERATED_BY)) return null;
  if (!file) throw new InvalidThemeError(`${THEME_DEFINITION_PATH} isn't valid JSON.`);
  const theme = parseThemeDefinition(file.theme);
  const basedOn = typeof file.basedOn === 'string' ? file.basedOn : null;
  const expected = renderThemeFiles(theme, basedOn);
  // Only the CSS decides: a hand edit to theme.json always changes it,
  // whereas docs/theme.md also changes when a Riff update rewords the
  // guide, which shouldn't read as "the theme is out of sync". The guide
  // is refreshed on the next save.
  const inSync = Object.entries(expected)
    .filter(([relative]) => relative.startsWith(`${THEME_DIR}/`) && relative !== THEME_DEFINITION_PATH)
    .every(([relative, content]) => {
      try {
        return readFileSync(path.join(repoRoot, relative), 'utf8') === content;
      } catch {
        return false;
      }
    });
  return { theme, basedOn, inSync };
}

export function summarizeAppTheme(repoRoot: string): AppThemeSummary | null {
  let current: AppTheme | null;
  try {
    current = readAppTheme(repoRoot);
  } catch {
    return null;
  }
  if (!current) return null;
  const preset = current.basedOn ? findThemePreset(current.basedOn) : undefined;
  return {
    name: current.theme.name,
    basedOn: current.basedOn,
    customized: !preset || !sameTheme(current.theme, presetDefinition(preset)),
    inSync: current.inSync,
  };
}

/**
 * Writes `theme` as the app's theme.json, regenerates everything derived
 * from it, and commits those paths on the base branch, so every session
 * branch cut afterwards starts with it. Refuses on any other branch rather
 * than slipping theme files into an in-progress feature branch.
 */
export async function saveAppTheme(app: AppConfig, input: unknown, basedOn: string | null): Promise<ThemeApplyResult> {
  let theme: ThemeDefinition;
  try {
    theme = parseThemeDefinition(input);
  } catch (err) {
    throw new ThemeApplyError((err as Error).message);
  }
  if (basedOn !== null && !findThemePreset(basedOn)) basedOn = null;

  return withRepoLock(app.repoRoot, async () => {
    const baseBranch = baseBranchFor(app);
    const branch = await currentBranch(app.repoRoot);
    if (branch !== baseBranch) {
      throw new ThemeApplyError(
        `${app.name} has "${branch}" checked out. Check out ${baseBranch} first, because the theme is committed there so every session branch picks it up.`
      );
    }
    if (existsSync(path.join(app.repoRoot, THEME_DIR)) && !isOurs(app.repoRoot)) {
      throw new ThemeApplyError(
        `${app.repoRoot}/${THEME_DIR}/ already exists and wasn't generated by Dev Sessions. Rename or remove it to apply a theme.`
      );
    }

    let previous: AppTheme | null = null;
    try {
      previous = readAppTheme(app.repoRoot);
    } catch {
      // an invalid hand edit is simply replaced
    }

    const files = renderThemeFiles(theme, basedOn);
    for (const [relative, content] of Object.entries(files)) {
      const absolute = path.join(app.repoRoot, relative);
      await fs.mkdir(path.dirname(absolute), { recursive: true });
      await fs.writeFile(absolute, content, 'utf8');
    }

    const summary = summarizeAppTheme(app.repoRoot)!;
    const warnings: string[] = [];
    const verb = !previous ? 'apply' : previous.theme.name === theme.name ? 'update' : 'switch to';
    const commit = await commitPaths(app.repoRoot, Object.keys(files), `style: ${verb} ${theme.name} UI theme`);
    if (commit === 'unchanged') return { theme: summary, actions: [`${theme.name} is already applied and up to date.`], warnings };

    const actions = [
      !previous
        ? `Wrote the ${theme.name} theme to ${THEME_DEFINITION_PATH}, generated its CSS and ${THEME_DOC_PATH}.`
        : previous.theme.name !== theme.name
          ? `Switched the theme from ${previous.theme.name} to ${theme.name} and regenerated its CSS.`
          : `Saved your changes to ${theme.name} and regenerated its CSS.`,
    ];
    if (commit === 'committed') actions.push(`Committed it on ${baseBranch}.`);
    if (commit === 'no-identity') {
      warnings.push(`Git has no user.name/user.email configured, so the theme files weren't committed. Commit them on ${baseBranch} before starting a coding stage.`);
    }
    if (!previous) {
      actions.push(`The coding agents will import ${THEME_DIR}/index.css at the app's root entry the next time they build UI.`);
    }
    return { theme: summary, actions, warnings };
  });
}

export async function applyThemePreset(app: AppConfig, presetId: string): Promise<ThemeApplyResult> {
  const preset = findThemePreset(presetId);
  if (!preset) throw new ThemeApplyError(`Unknown theme "${presetId}".`);
  return saveAppTheme(app, presetDefinition(preset), preset.id);
}

/** After a hand edit of theme.json: regenerate the CSS and docs from it. */
export async function regenerateAppTheme(app: AppConfig): Promise<ThemeApplyResult> {
  let current: AppTheme | null;
  try {
    current = readAppTheme(app.repoRoot);
  } catch (err) {
    throw new ThemeApplyError((err as Error).message);
  }
  if (!current) throw new ThemeApplyError(`${app.name} has no ${THEME_DEFINITION_PATH} to regenerate from.`);
  return saveAppTheme(app, current.theme, current.basedOn);
}

/** Where a new or proposed theme starts: the app's current theme, else the first preset. */
export function startingTheme(repoRoot: string): { theme: ThemeDefinition; basedOn: string | null } {
  try {
    const current = readAppTheme(repoRoot);
    if (current) return { theme: current.theme, basedOn: current.basedOn };
  } catch {
    // invalid hand edit — fall back to a preset
  }
  return { theme: presetDefinition(THEME_PRESETS[0]), basedOn: THEME_PRESETS[0].id };
}
