import { promises as fs } from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';
import type { ParsedAttachment } from '../agents/attachments.js';
import type { SessionMeetingSource } from './session.js';

const MAX_SOURCE_CHARS = 200_000;

export interface MeetingSourceInput {
  meetingId: string;
  meetingTitle: string;
  meetingDate?: string | null;
  transcript: string;
  summary?: string | null;
}

export function validateMeetingSourceInput(input: unknown): string | null {
  if (!input || typeof input !== 'object') return 'source must be an object';
  const s = input as Record<string, unknown>;
  if (typeof s.meetingId !== 'string' || !s.meetingId.trim()) return 'source.meetingId is required';
  if (typeof s.meetingTitle !== 'string') return 'source.meetingTitle is required';
  if (typeof s.transcript !== 'string' || !s.transcript.trim()) return 'source.transcript is empty';
  if (s.summary != null && typeof s.summary !== 'string') return 'source.summary must be a string';
  return null;
}

export async function writeMeetingSource(sessionId: string, input: MeetingSourceInput): Promise<SessionMeetingSource> {
  await fs.mkdir(config.meetingSourcesDir, { recursive: true });
  const filePath = path.join(config.meetingSourcesDir, `${sessionId}.md`);
  const summary = input.summary?.trim() || null;

  const parts = [
    `# Meeting: ${input.meetingTitle}`,
    input.meetingDate ? `Date: ${input.meetingDate}` : null,
    summary ? `## Meeting summary (AI-generated by Meetily)\n\n${summary}` : null,
    `## Transcript\n\n${input.transcript.trim()}`,
  ].filter(Boolean);

  await fs.writeFile(filePath, `${parts.join('\n\n')}\n`, 'utf8');

  return {
    meetingId: input.meetingId,
    meetingTitle: input.meetingTitle,
    meetingDate: input.meetingDate ?? null,
    transcriptPath: path.relative(config.harnessRoot, filePath),
    includesSummary: Boolean(summary),
  };
}

export async function readMeetingSourceAttachment(source: SessionMeetingSource): Promise<ParsedAttachment> {
  let text = await fs.readFile(path.join(config.harnessRoot, source.transcriptPath), 'utf8');
  if (text.length > MAX_SOURCE_CHARS) {
    const omitted = text.length - MAX_SOURCE_CHARS;
    text = `${text.slice(0, MAX_SOURCE_CHARS)}\n\n[... truncated, ${omitted.toLocaleString()} more characters omitted ...]`;
  }
  return { name: `meeting-transcript-${source.meetingTitle || source.meetingId}.md`, text };
}

export async function removeMeetingSource(source: SessionMeetingSource | null): Promise<void> {
  if (!source) return;
  await fs.rm(path.join(config.harnessRoot, source.transcriptPath), { force: true });
}
